### ISSUE TITLE
release notes are broken on origen-testers website

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen_testers#50]
http://origen-sdk.org/release_notes

**Comment by ginty** [comment]
OK fixed now, the issue was broken links from here: http://origen-sdk.org/testers/

@pderouen, this seems related to the deploys you made yesterday, the link website has the same issue and I haven't fixed that one yet - http://origen-sdk.org/OrigenLink/

I didn't change any here other than to re-run `origen web compile -r`.

The links will generate like that when it thinks the -r switch is missing, since that path needs to be slightly different for local viewing.

So if your flow was `origen web compile` -> manually copy to the Git repo and checkin, then that would explain it.

If not, then it must be something to do with Windows?

**Comment by ginty** [comment]
JTAG is ok interestingly: http://origen-sdk.org/jtag/

**Comment by pderouen** [comment]
@ginty, for both link and testers I did origen web compile -a, followed by origen web deploy.
For jtag, origen rc tag made it all the way through the web deploy step.

**Comment by ginty** [comment]
I think `origen web deploy` must be to effectively just copy over what you have already generated, which in your case would have been with local links.

I wonder if we should just deprecate/remove `origen web deploy`, to be honest I forgot it existed and haven't used it for years.

**Comment by pderouen** [comment]
If there is still a use case for web deploy, a warning message followed by a confirmation that you want to continue would do the trick.  If there's no use case for it, I'd vote for removal.

**Comment by pderouen** [comment]
Fixed release notes link for OrigenLink.
