### ISSUE TITLE
V93K test method parameters' types question

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen_testers#75]
Hi,

We consume an ASCII file from Verigy that contains all test methods and their parameters, including parameter default values.  We are seeing duplicate units of measures in the tf file.  Is there some logic in the generator such that any default values are hard-coding what the unit of measure is? 

Here is and example of what we programmed for our test method params:

~~~ruby
     test_modules(:pcie).define_params :param_default do |p|
        p.tm.Parametric.Measurement0.HighLimitSpecVal = '1.3[V]'
~~~

Here is what we are seeing in the .tf fle:

~~~shell
"Parametric.Measurement0.HighLimitSpecVal" = "1.3[V][A]";
~~~

When I look at what I am feeding to the 'add_tml' method I can see that the default value references amps.

~~~ruby
#<struct Translator::TestMethodParam name="Parametric.Measurement0.HighLimitSpecVal", type=:current, default_value="0[A]">,
~~~

I can see that I am sending it a type of :current so that must be what is causing this.  Should I just send everything as as :string or will that choke?

thx

**Comment by ginty** [comment]
I think you probably can send everything as string and it should work.

Alternatively, improve this format method to make it stop appending a unit if there is already one there:
https://github.com/Origen-SDK/origen_testers/blob/master/lib/origen_testers/smartest_based_tester/base/test_method.rb#L88

**Comment by info-rchitect** [comment]
@ginty sending everything as a string did work.  I really don't think that format method is doing anything wrong as I did tell it to expect a :current.  Wouldn't that allow people to force improper values when some test interface 'expert' has chosen a method for the company/group?

**Comment by ginty** [comment]
Not sure tbh.
We are not really doing anything with these units on the Origen side, we are currently taking the approach that in the Origen source code people can use the Origen unit helpers, `.mV`, `.uA`, etc. but then these just get converted to their equivalent whole unit value when rendered to 93K.
I suspect that appending "[V]" and "[A]" to the 93K code doesn't really do anything and is probably equivalent to not supplying any unit at all, though I have not really tried it without.

**Comment by ginty** [comment]
As an aside (if you ever feel so inclined to add it), it would be nice if calling `10.mV` and so on in Origen converted the number to a NumberWithUnits object instance, which would inherit from and behave like the regular number object, but which would add a `.units` method to allow the assigned units to be carried forward and retrieved by downstream code.
That would make rendering proper units to something like the V93K trivial, instead of the significant effort in trying to work out what it should be from the whole unit version (which is why I took a pass on it and went for the easy option in the current V93K generator).

**Comment by info-rchitect** [comment]
@ginty i will take that PR for the NumberWithUnits
